config/routes.rb
Rails.application.routes.draw do
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :number_of_guests, presence: true
  validates :price_per_night, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(params_flat)
    @flat.save
    if @flat.save
      redirect_to flats_path
    else
      render 'new'
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(params_flat)
    if @flat.update(params_flat)
      redirect_to @flat
    else
      render 'new'
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy40
  end

  private

  def params_flat
    params.require(:flat).permit(:name, :address, :description, :image, :wifi, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="banner">
  <div class="title">
    <h1>Simple Airbnb</h1>
  </div>
  <div class="button">
    <%= link_to 'Add a flat', new_flat_path, id:'btn' %>
  </div>
</div>

<div class="container">

  <div class="cards">

      <% @flats.each do |flat| %>

        <div class="card">
          <div class="card-content" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= flat.image %>);">
            <div class="card-category">
              <%= flat.price_per_night %>€
              <i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>
            </div>
            <div class="card-description">
              <h2><%= flat.name %></h2>
              <p><%= flat.address %></p>
            </div>
          </div>
          <div class="card-info">
            <%= link_to 'More info', flat %>
          </div>
        </div>
      <% end %>

  </div>

</div>

app/views/flats/new.html.erb
<div class="container">
  <h1>Add your flat</h1>

  <div id="flat_form">
    <%= simple_form_for(@flat) do |f|  %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <%= f.input :image %>
      <%= f.input :wifi %>
      <%= f.button :submit, id:'btn' %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner-flat" style="background: url(<%= @flat.image %>) center no-repeat" >
  <h1><%= @flat.name %></h1>
</div>

<div class="container">
  <div class="desc-container">
    <div class="desc-box">
      <p><i class="fas fa-map-marker-alt"></i> <%= @flat.address %></p>
      <p><%= @flat.description %></p>
    </div>
    <div class="desc-info">
      <p><%= @flat.price_per_night %>€</p>
      <p><i class="fas fa-user-friends"></i> <%= @flat.number_of_guests %></p>
      <% if @flat.wifi %>
        <p><i class="fas fa-wifi"></i></p>
      <% end %>
    </div>
  </div>
  <div class="show-button">
    <%= link_to 'Home', flats_path, id:'btn' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>